# Generated by Django 5.1.15 on 2025-12-18 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text='Store the Symbol of the Company To Search', max_length=20)),
                ('company', models.CharField(help_text='Store the Name of the Company To Search', max_length=300)),
                ('stock_held', models.IntegerField(default=0, help_text='Store the Number of Stocks held of that Company by and Individual')),
                ('dated_on', models.DateTimeField(default=django.utils.timezone.now, help_text='Store the Date When the Stock was Bought')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, help_text='Store the Date When the Entry was Created')),
                ('investment_value', models.DecimalField(decimal_places=2, help_text='Store the Initial Investment Value for the Stock', max_digits=20)),
            ],
            options={
                'db_table': 'user_requests',
            },
        ),
    ]
