# Generated by Django 5.1.15 on 2025-12-22 17:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='mystocks',
            field=models.BooleanField(default=False, help_text='Store the status for the Stock'),
        ),
        migrations.AddField(
            model_name='userrequests',
            name='user_id',
            field=models.IntegerField(default=0, help_text='Store the User ID of the Company To Search'),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='investment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Store the Initial Investment Value for the Stock', max_digits=20),
        ),
    ]
