# Generated by Django 5.1.15 on 2025-12-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userrequests_mystocks_userrequests_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='is_added',
            field=models.BooleanField(default=False, help_text='Store the Value if Request was Completed'),
        ),
    ]
