# Generated by Django 5.1.15 on 2025-12-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userrequests_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='dated_on',
            field=models.DateTimeField(help_text='Store the Date When the Stock was Bought'),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='investment_value',
            field=models.DecimalField(decimal_places=2, help_text='Store the Initial Investment Value for the Stock', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='stock_held',
            field=models.IntegerField(help_text='Store the Number of Stocks held of that Company by and Individual'),
        ),
    ]
