# Generated by Django 5.1.15 on 2025-12-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_userrequests_dated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='is_checked',
            field=models.BooleanField(default=False, help_text='Store the Value if Company was Initialized'),
        ),
    ]
