# Generated by Django 5.1.15 on 2025-12-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userrequests_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('symbol', models.CharField(max_length=32)),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('exchange', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tick_data',
                'managed': False,
            },
        ),
    ]
