export const marketData = [
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
  {
    title: "RELIANCE",
    description: "Reliance Industries Ltd",
    sector: "Energy",
    value: "₹2,892.35",
    change: "+45.20",
    daychange: "+1.59%",
    vol: "12.5M",
    cap: "19.5L Cr",
  },
]